### ISSUE TITLE
One globally coordinated strict lockdown

### ISSUE THREAD

**Issue by amalic** [NicolleLouis/celauco#1]
Can you add one single globally coordinated strict lockdown, where people get their groceries delivered instead of having to go to the supermarket?

My gut feeling is that we could have beaten Sars-nCoV right at the beginning within 4-6 weeks.

**Comment by NicolleLouis** [comment]
Hey, thanks for the feedback. You mean like another agent type being delivery man going from home to home to give groceries? And the other human are trying to stay home and avoid social contact

**Comment by amalic** [comment]
Exactly!

But considering that this agent is extrra cautious, and leaves the package in front of the door instead of handing it over directly.

**Comment by NicolleLouis** [comment]
Nice idea, I'm going to try it
